export const EnviormentKeys = {
  PORT: 'PORT',
  SESSION_MAXAGE: 'SESSION_MAXAGE',
  SESSION_SECRET: 'SESSION_SECRET',
  PUBLIC_KEY: 'PUBLIC_KEY',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRESIN',
  DB_HOST: 'DB_HOST',
  DB_NAME: 'DB_NAME',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',
};
